version: "3"

networks:
  fc2:
    driver: bridge
    
services:
  app:
    build: .
    container_name: simulator
    volumes:
     - .:/go/src
    # extra_hosts:
    #  - "host.docker.internal:172.17.0.1"
    networks:
      - fc2